### ISSUE TITLE
How can download my game without DLC?

### ISSUE THREAD

**Issue by Leonelvader** [PatnosDD/Cuphead-PS-VITA#10]
So how can I download my legit copy of the game in steam without the DLC? I have the error XD3_INVALID_INPUT, I read the instructions and I think the only thing I don't comply with is having the dlc installed

**Comment by Awesome-guyy** [comment]
@Leonelvader You need to right click cuphead, go to properties, DLC, and reinstall it. Make sure the DLC checkbox is disabled.
