### ISSUE TITLE
Question about another port

### ISSUE THREAD

**Issue by DeroPlayz** [PatnosDD/Cuphead-PS-VITA#11]
Sorry, I was just curious since there is no visible repo for it, but do you have the repo for pako forever? I have loved it in PS Vita and wanted to see the inner workings, and maybe help adapt the menus for console use.

**Comment by PatnosDD** [comment]
Hey, i dont think i still have the project on me.

**Comment by DeroPlayz** [comment]
Dang, gotcha. Do you think you'd be able to help me port the pako series? Not like active role per se, just answering questions on discord? If yes, add me @the_true_dero
