### ISSUE TITLE
lowering resolution doesnt change performance

### ISSUE THREAD

**Issue by BoomBlash** [PatnosDD/Cuphead-PS-VITA#12]
i changed the resolution to 240p and the performance was the same, i assume the issue was that the game still rendered the game at the Vitas native resolution, it is probably something that can be fixed

**Comment by PatnosDD** [comment]
The resolution changes would affect performance IF we were GPU-bound, not CPU-bound.

**Comment by BoomBlash** [comment]
oh thanks, is  it updated to the newest VitaGL version or is it DirectX based?

**Comment by PatnosDD** [comment]
Unity based ports don't use community made vita sdk.

**Comment by BoomBlash** [comment]
oh, anyways just a question

can you update the Untitled Goose game port for better optimization

**Comment by BoomBlash** [comment]
also another question (if you dont mind responding) , is a Cave Story+ port possible?

**Comment by PatnosDD** [comment]
You can ask those questions on my discord server.
