### ISSUE TITLE
Hello, Sorry if a lil annoying but why is the port crashing randomly

### ISSUE THREAD

**Issue by BoomBlash** [PatnosDD/Cuphead-PS-VITA#14]
i loaded up a boss and the game crashed  for no reason

Any fix possible?

Have a nice day tho :)

**Comment by BoomBlash** [comment]
also sorry for closing and reopening this issue, just a me getting confused :)

**Comment by PatnosDD** [comment]
Provide more information so the issue can be fixed. Video for example of the issue

**Comment by BoomBlash** [comment]
well i loaded Threatenin Zeppelin and it crashed

not sure what the problem was

**Comment by PatnosDD** [comment]
Please upload a video showcasing the issue.

**Comment by BoomBlash** [comment]
sorry didnt record

probably was just a crash issue of the port

anyways

bye!
