### ISSUE TITLE
XD3_INVALID_INPUT

### ISSUE THREAD

**Issue by SuperGameBlade** [PatnosDD/Cuphead-PS-VITA#15]
pretty sure i read the readme right but im still getting "XD3_INVALID_INPUT".

Fresh DL copy of cuphead from steam NO DLC

<img width="675" alt="Screenshot 2024-12-24 223201" src="https://github.com/user-attachments/assets/9a93dce9-6446-4a91-9a14-c102bbd271e3" />
<img width="587" alt="Screenshot 2024-12-24 223327" src="https://github.com/user-attachments/assets/ea8c09d4-feb1-4e8d-8bd4-e13f2b769ce0" />
<img width="705" alt="Screenshot 2024-12-24 223554" src="https://github.com/user-attachments/assets/0154c38c-2b3b-4762-ae64-3e3d0bdafcce" />
<img width="610" alt="Screenshot 2024-12-24 224110" src="https://github.com/user-attachments/assets/67cf4aa4-fbee-4846-b1fc-2c61835ec29b" />

any ideas on what to do?

**Comment by PatnosDD** [comment]
Hey, make sure you dont have DLC installed

**Comment by Awesome-guyy** [comment]
@SuperGameBlade Make sure in steam you right click cuphead, go to properties, DLC, and uncheck the dlc, and redownload it.

**Comment by SuperGameBlade** [comment]
> @SuperGameBlade Make sure in steam you right click cuphead, go to properties, DLC, and uncheck the dlc, and redownload it.

Sorry if I worded it weird.   I deleted and re-downloaded so I have a fresh copy of copy of cuphead with NO dlc, I dont even own the DLC. 
Could it be because I never even ran the cuphead application on the pc I was using?

**Comment by SuperGameBlade** [comment]
> @SuperGameBlade Make sure in steam you right click cuphead, go to properties, DLC, and uncheck the dlc, and redownload it.

Sorry if I worded it weird.   I deleted and re-downloaded so I have a fresh copy of copy of cuphead with NO dlc, I dont even own the DLC. 
Could it be because I never even ran the cuphead application on the pc I was using?

**Comment by SuperGameBlade** [comment]
> @SuperGameBlade Make sure in steam you right click cuphead, go to properties, DLC, and uncheck the dlc, and redownload it.

Ok if there is free DLC I may have it installed but I only own base game. So I'll check later thanks for the reply.
