### ISSUE TITLE
Museum 1 glitched

### ISSUE THREAD

**Issue by Flewxxx** [PatnosDD/Cuphead-PS-VITA#2]
The level « Museum 1 » is glitched and won’t spawn the ennemies, so you’re stuck.

**Comment by PatnosDD** [comment]
Update the game. Issue is long fixed

**Comment by Flewxxx** [comment]
can you send me a media fire or mega link for the updated game? i’ve only got an old copy

**Comment by Flewxxx** [comment]
do i need to update game or vpk ? cuz im on the latest vpk g

**Comment by PatnosDD** [comment]
Update the game by yourself. Im not going to assist you with pirating the game.


Instructions clearly say that you also need to update the game files, not just vpk.

**Comment by Flewxxx** [comment]
could i please just get the game files i don’t have acces to my pc for all the vacations rn please bro you literally have to drag and drop a file please it would save my vacations tbh

**Comment by PatnosDD** [comment]
I already gave you a final answer.
