### ISSUE TITLE
Resolution doesn't save on quit out

### ISSUE THREAD

**Issue by roundtent** [PatnosDD/Cuphead-PS-VITA#3]
The resolution you pick doesn't save once you quit out. When you reopen the game, it goes back to the default (960x544).

**Comment by PatnosDD** [comment]
Thanks for reporting that. Resolution option is planned to be removed since there isn't much point of it on vita.

**Comment by roundtent** [comment]
Ah I see, nvm then and thanks for the comment :).

I will miss the resolution option though, as it lets you blur the UI slightly to bring it more inline with the games  (also blurry) art style.

Thanks for the amazing port and keep up the good work!
