### ISSUE TITLE
Old film grain effect not working

### ISSUE THREAD

**Issue by Girotin** [PatnosDD/Cuphead-PS-VITA#4]
New release says it has the old grain effect now, but nothing appears;

It's my first install, game seems as expected despite that.

**Comment by PatnosDD** [comment]
If you just update the vpk file(even tho GitHub page told you to also update game files), obviously nothing new will be added to the game

**Comment by Girotin** [comment]
Oh ok, sorry, thx for the quick answer

**Comment by Girotin** [comment]
Oh ok, sorry, thx for the quick answer
