### ISSUE TITLE
Existing Game impossible to launch (game Freeze)

### ISSUE THREAD

**Issue by Slanseith** [PatnosDD/Cuphead-PS-VITA#6]
Hi,
I've got an Issue with the game (0.70) on Vita3K Android (V0.2.0, latest).
All is perfect with new game (no save created)
but when i quit and launch the game later, it freeze just before the start menu (with Start, options etc...)

the only way i've found to play it again is to delete my save files...

Any idea of how to fix that ?

Thanks for your help

**Comment by PatnosDD** [comment]
Port is intended to work on PlayStation Vita, not emulator of it

**Comment by Slanseith** [comment]
i know, but everything is just perfect with the game, i've beaten  3 bosses without bug or crash.
it's only when i start the game later with saves...
i've seen this in your update log :
"Fixed crash which occurred when the user exited the existing game and started a new one."
it seems to be my issue

I've purchased the game on Steam and Switch, but wanted to give a try on my phone

thanks if you have any Clue

**Comment by PatnosDD** [comment]
The port saves save files in ux0:/data, which does not exist in emulator vita3k

**Comment by Slanseith** [comment]
my saves are in Vita / Ux0 / data
![20240612_170840](https://github.com/PatnosDD/Cuphead-PS-VITA/assets/172516585/7cbc9c06-f3e6-40e3-85d8-ab68cc877c42)

**Comment by PatnosDD** [comment]
Either way port is not made for vita3k since overall unity based games are not working on it properly in some cases
