### ISSUE TITLE
not APPLYPATCH

### ISSUE THREAD

**Issue by ra70155** [PatnosDD/Cuphead-PS-VITA#8]
hey i tried to APPLYPATCH the cup head steam but i always get a error  i didn't install the DLC 
![3](https://github.com/user-attachments/assets/411912c3-41eb-4c4e-9e64-7f78f4d6e6d5)
do you know the problem

**Comment by mf-rl** [comment]
![image](https://github.com/user-attachments/assets/9ea168cd-8a4f-4a52-a5e8-6e1eddb900c9)

**Comment by PatnosDD** [comment]
Maybe show me the folder at least? Instead of hiding it

**Comment by PatnosDD** [comment]
Why is there Cuphead_Data folder instead of Cuphead folder? Read the instructions

**Comment by ra70155** [comment]
ok thank you it worked
